name: github_actions_conditional
on: workflow_dispatch
jobs:
  test_gha_if_condition:
    runs-on: ubuntu-latest
    steps:
        - name : Print Hello
          id: print_hello
          run: |
            echo "GOODBYE..."
            exit 0
            #even if this step fails follow the next step
        - name : Print Goodbye
          if: failure() && steps.print_hello.outcome == 'failure'
          run : echo "I am printing beacuse step 1 failed"
  Sequential_job:
    needs: test_gha_if_condition
    runs-on : ubuntu-latest
    steps:
        - name : To run sequential
          run : echo "This is conditional run"
        - name : Another if_condition
          id: if_2
          run: |
            echo "Just a test"
            exit 1
        - name : next_condition
          if: always() && steps.if_2.outcome == 'success'
          run: echo "This is a success"
          
          
